---
title: FileAccessViolationException
second_title: Aspose.Email بريد إلكتروني لمرجع .NET API
description: تهيئة مثيل جديد للفئة برسالة خطأ افتراضية.
type: docs
weight: 10
url: /ar/net/aspose.email.mapi/fileaccessviolationexception/fileaccessviolationexception/
---
## FileAccessViolationException() {#constructor}

تهيئة مثيل جديد للفئة برسالة خطأ افتراضية.

```csharp
public FileAccessViolationException()
```

### أنظر أيضا

* class [FileAccessViolationException](../../fileaccessviolationexception)
* مساحة الاسم [Aspose.Email.Mapi](../../fileaccessviolationexception)
* المجسم [Aspose.Email](../../../)

---

## FileAccessViolationException(string) {#constructor_1}

تهيئة مثيل جديد للفئة برسالة خطأ محددة.

```csharp
public FileAccessViolationException(string message)
```

| معامل | يكتب | وصف |
| --- | --- | --- |
| message | String | رسالة خطأ. |

### أنظر أيضا

* class [FileAccessViolationException](../../fileaccessviolationexception)
* مساحة الاسم [Aspose.Email.Mapi](../../fileaccessviolationexception)
* المجسم [Aspose.Email](../../../)

---

## FileAccessViolationException(string, Exception) {#constructor_2}

يقوم بتهيئة مثيل جديد لفئة الاستثناء مع رسالة خطأ محددة ومرجع إلى الاستثناء inner الذي هو سبب هذا الاستثناء.

```csharp
public FileAccessViolationException(string message, Exception innerException)
```

| معامل | يكتب | وصف |
| --- | --- | --- |
| message | String | رسالة الخطأ التي توضح سبب الاستثناء. |
| innerException | Exception | الاستثناء الذي هو سبب الاستثناء الحالي. إذا لم تكن معلمة innerException عبارة عن مرجع NULL (لا شيء في Visual Basic) ، يتم رفع الاستثناء الحالي إلى في كتلة catch تتعامل مع الاستثناء الداخلي. |

### أنظر أيضا

* class [FileAccessViolationException](../../fileaccessviolationexception)
* مساحة الاسم [Aspose.Email.Mapi](../../fileaccessviolationexception)
* المجسم [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
