---
title: AsposeBadServerResponceException
second_title: Aspose.Email per riferimento all'API .NET
description: Inizializza una nuova istanza diAsposeBadServerResponceExceptionaspose.email/asposebadserverresponceexception classe con un messaggio di errore specificato.
type: docs
weight: 10
url: /it/net/aspose.email/asposebadserverresponceexception/asposebadserverresponceexception/
---
## AsposeBadServerResponceException(string) {#constructor_2}

Inizializza una nuova istanza di[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe con un messaggio di errore specificato.

```csharp
public AsposeBadServerResponceException(string message)
```

| Parametro | Tipo | Descrizione |
| --- | --- | --- |
| message | String | Un messaggio che descrive l'errore. |

### Guarda anche

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* spazio dei nomi [Aspose.Email](../../asposebadserverresponceexception)
* assemblea [Aspose.Email](../../../)

---

## AsposeBadServerResponceException() {#constructor}

Inizializza una nuova istanza di[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe.

```csharp
public AsposeBadServerResponceException()
```

### Guarda anche

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* spazio dei nomi [Aspose.Email](../../asposebadserverresponceexception)
* assemblea [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(string, Exception) {#constructor_3}

Inizializza una nuova istanza di[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe con un messaggio di errore specificato e un riferimento all'eccezione interna che è la causa di questa eccezione.

```csharp
public AsposeBadServerResponceException(string message, Exception innerException)
```

| Parametro | Tipo | Descrizione |
| --- | --- | --- |
| message | String | Il messaggio di errore che spiega il motivo dell'eccezione. |
| innerException | Exception | L'eccezione che è la causa dell'eccezione corrente o un riferimento null (Nothing in Visual Basic) se non viene specificata alcuna eccezione interna. |

### Guarda anche

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* spazio dei nomi [Aspose.Email](../../asposebadserverresponceexception)
* assemblea [Aspose.Email](../../../)

---

## AsposeBadServerResponceException(Exception) {#constructor_1}

Inizializza una nuova istanza di[`AsposeBadServerResponceException`](../../asposebadserverresponceexception) classe con un riferimento all'eccezione interna che è la causa di questa eccezione.

```csharp
public AsposeBadServerResponceException(Exception innerException)
```

| Parametro | Tipo | Descrizione |
| --- | --- | --- |
| innerException | Exception | L'eccezione che è la causa dell'eccezione corrente o un riferimento null (Nothing in Visual Basic) se non viene specificata alcuna eccezione interna. |

### Guarda anche

* class [AsposeBadServerResponceException](../../asposebadserverresponceexception)
* spazio dei nomi [Aspose.Email](../../asposebadserverresponceexception)
* assemblea [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
