---
title: ActiveSyncException
second_title: Aspose.Email für .NET-API-Referenz
description: Initialisiert eine neue Instanz vonActiveSyncExceptionaspose.email/activesyncexception Klasse mit einer bestimmten Fehlermeldung.
type: docs
weight: 10
url: /de/net/aspose.email/activesyncexception/activesyncexception/
---
## ActiveSyncException(string) {#constructor_2}

Initialisiert eine neue Instanz von[`ActiveSyncException`](../../activesyncexception) Klasse mit einer bestimmten Fehlermeldung.

```csharp
public ActiveSyncException(string message)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| message | String | Eine Meldung, die den Fehler beschreibt. |

### Siehe auch

* class [ActiveSyncException](../../activesyncexception)
* namensraum [Aspose.Email](../../activesyncexception)
* Montage [Aspose.Email](../../../)

---

## ActiveSyncException() {#constructor}

Initialisiert eine neue Instanz von[`ActiveSyncException`](../../activesyncexception) Klasse.

```csharp
public ActiveSyncException()
```

### Siehe auch

* class [ActiveSyncException](../../activesyncexception)
* namensraum [Aspose.Email](../../activesyncexception)
* Montage [Aspose.Email](../../../)

---

## ActiveSyncException(string, Exception) {#constructor_3}

Initialisiert eine neue Instanz von[`ActiveSyncException`](../../activesyncexception) Klasse mit einer angegebenen Fehlermeldung und einem Verweis auf die innere Ausnahme, die diese Ausnahme verursacht hat.

```csharp
public ActiveSyncException(string message, Exception innerException)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| message | String | Die Fehlermeldung, die den Grund für die Ausnahme erklärt. |
| innerException | Exception | Die Ausnahme, die die Ursache der aktuellen Ausnahme ist, oder ein Nullverweis (Nothing in Visual Basic), wenn keine innere Ausnahme angegeben ist. |

### Siehe auch

* class [ActiveSyncException](../../activesyncexception)
* namensraum [Aspose.Email](../../activesyncexception)
* Montage [Aspose.Email](../../../)

---

## ActiveSyncException(Exception) {#constructor_1}

Initialisiert eine neue Instanz von[`ActiveSyncException`](../../activesyncexception) Klasse mit einem Verweis auf die innere Ausnahme, die die Ursache dieser Ausnahme ist.

```csharp
public ActiveSyncException(Exception innerException)
```

| Parameter | Typ | Beschreibung |
| --- | --- | --- |
| innerException | Exception | Die Ausnahme, die die Ursache der aktuellen Ausnahme ist, oder ein Nullverweis (Nothing in Visual Basic), wenn keine innere Ausnahme angegeben ist. |

### Siehe auch

* class [ActiveSyncException](../../activesyncexception)
* namensraum [Aspose.Email](../../activesyncexception)
* Montage [Aspose.Email](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.Email.dll -->
